all_students_data = [
    {
        "user": {
            "username": "whitekristen",
            "first_name": "David",
            "last_name": "Miller",
            "email": "mcampbell@example.net",
            "date_of_birth": "1968-08-26",
            "address": "4657 Moore Plains\nTylermouth, WV 41079",
            "sex": "M",
        },
        "admission_number": "9237",
        "date_of_admission": "2020-09-06",
        "date_of_graduation": "2026-04-01",
        "guardian": None,
    },
    {
        "user": {
            "username": "xwagner",
            "first_name": "Gregory",
            "last_name": "Murphy",
            "email": "michaelking@example.net",
            "date_of_birth": "1965-04-08",
            "address": "88464 Crystal Manor\nColleenside, NM 30599",
            "sex": "M",
        },
        "admission_number": "6874",
        "date_of_admission": "2023-05-01",
        "date_of_graduation": "2026-10-11",
        "guardian": None,
    },
    {
        "user": {
            "username": "cynthiasanders",
            "first_name": "Jessica",
            "last_name": "Jones",
            "email": "manuel97@example.org",
            "date_of_birth": "1960-02-23",
            "address": "USCGC Meyer\nFPO AA 96736",
            "sex": "M",
            "institution": 10,
        },
        "admission_number": "9431",
        "date_of_admission": "2021-05-26",
        "date_of_graduation": "2027-08-06",
        "guardian": None,
    },
    {
        "user": {
            "username": "zberger",
            "first_name": "Susan",
            "last_name": "George",
            "email": "barbara70@example.org",
            "date_of_birth": "1978-09-23",
            "address": "742 Sandra Club Suite 176\nNortonmouth, MN 77336",
            "sex": "M",
        },
        "admission_number": "3776",
        "date_of_admission": "2022-05-20",
        "date_of_graduation": "2025-11-25",
        "guardian": None,
    },
]

all_guardians_data = [
    {
        "user": {
            "username": "smithteresa",
            "first_name": "Rebecca",
            "last_name": "Rodgers",
            "email": "frank01@example.org",
            "date_of_birth": "1944-09-13",
            "address": "9621 Caitlyn Squares Suite 298\nRobertchester, ND 98866",
            "sex": "F",
            "institution": 0,
        },
        "wards": [],
        "profession": "Lawyer",
        "relationship": "Father",
    },
    {
        "user": {
            "username": "gabriellaharmon",
            "first_name": "Katherine",
            "last_name": "Woods",
            "email": "mathewsdavid@example.com",
            "date_of_birth": "1932-05-07",
            "address": "8276 Simmons Ford\nEast Terriborough, AK 71349",
            "sex": "F",
            "institution": 0,
        },
        "wards": [],
        "profession": "Risk manager",
        "relationship": "Guardian",
    },
    {
        "user": {
            "username": "joneswilliam",
            "first_name": "Robert",
            "last_name": "Chapman",
            "email": "erollins@example.com",
            "date_of_birth": "1943-08-05",
            "address": "886 Danielle Parkways\nRodriguezburgh, NJ 95265",
            "sex": "M",
            "institution": 0,
        },
        "wards": [],
        "profession": "Fine artist",
        "relationship": "Mother",
    },
    {
        "user": {
            "username": "fbowen",
            "first_name": "Pamela",
            "last_name": "Cook",
            "email": "jacob58@example.com",
            "date_of_birth": "1959-03-07",
            "address": "675 Howard Views\nPort Markshire, PA 93142",
            "sex": "F",
            "institution": 0,
        },
        "wards": [],
        "profession": "Network engineer",
        "relationship": "Guardian",
    },
    {
        "user": {
            "username": "twade",
            "first_name": "Chelsea",
            "last_name": "Parker",
            "email": "james73@example.org",
            "date_of_birth": "2016-08-17",
            "address": "0391 Patterson Streets\nPort Heatherview, OR 12165",
            "sex": "F",
            "institution": 0,
        },
        "wards": [],
        "profession": "Medical laboratory scientific officer",
        "relationship": "Mother",
    },
]
